### ISSUE TITLE
Unicorns when pushing to Rubygems

### ISSUE THREAD

**Issue by eileencodes** [rubygems/rubygems.org#1678] opened 2017-09-27 17:08 UTC
Howdy!

I don't know if this is the right place for this issue, let me know if it's not and I'll move it.

The last 2 times I've pushed gems to Rubygems I've gotten a Unicorn! during the push. This happened on the `rails` gem of Rails when I was pushing `4.2.10.rc1` and happened today when I was pushing the final release but failed on `activerecord` so I had to push the remaining gems manually instead of using our rake task that pushes them all individually.

I'm not sure if this is common, but I've released Rails a fair amount and haven't seen this before. I forgot to grab a screenshot but the push command essentially hits a Unicorn and what's returned is the HTML for the Unicorn page you would hit on the site, but instead happens on a push.

Let me know if you need more information.

**Comment by dwradcliffe** [comment] 2017-09-27 17:32
Thanks for the report. I'll dig into this and see if I can find out what happened.

**Comment by shevegen** [comment] 2017-09-28 18:07
I also noticed some unicorn-error on rubygems.org, although not when I pushed any of my gems myself, but instead a while ago it seems as if rubygems.org had some problem where I could see some error page. It has not yet happened to any of my gems really, or at the least not in any way that it impeded me in any way, but I can confirm that there may have been more ponicorns as of late, I mean, unicorns. I can't give a single example ~2 years ago but I think I may have seen unicorns 2 or 3 times or so, some days or even a few weeks ago. But not in regards to any of my gems ... I actually can not even remember where or how I saw it, I just did other things and lateron everything was fine again anyway. May be a heisen-unicorn ... :\

**Comment by colby-swandale** [comment] 2017-10-30 13:01
@dwradcliffe did you solve this issue? Can this be closed?

**Comment by bf4** [comment] 2017-11-02 15:12
Related to https://github.com/rubygems/rubygems.org/issues/1683

**Comment by josepjaume** [comment] 2017-12-15 10:42
I'm also seeing unicorns lately when releasing https://github.com/decidim/decidm (which is a multigem). It turns out the gem gets released anyway, though!

**Comment by hsbt** [comment] 2022-06-14 06:51
This issue was reported 5 years ago. I will close this.

**Closed by hsbt** 2022-06-14 06:51 UTC
Labels: infra
