### ISSUE TITLE
Differences between 

### ISSUE THREAD

**Issue by Peuf54** [rubygems/rubygems.org#3954] opened 2023-07-24 07:56 UTC
Hi there, 

I have a question/issue regarding the API of Rubygems. The support ask me to place my issue here.
I observed some differences between endpoint : /api/v1/activity/just_updated.json, and the releases page.

## Steps to Reproduce

Here a quick video where I show you an example ~2 mins : https://www.loom.com/share/a6f743c9638d4b9abaf8967af1180c44?sid=da34ba5e-9fc2-4be0-8fc4-8e05a002011d
If you want to test :
1. Copy the return of https://rubygems.org/api/v1/activity/just_updated.json
2. Open https://rubygems.org/news
3. Compare the 30-50 firsts results

## Expected Behavior

I think this endpoint : https://rubygems.org/api/v1/activity/just_updated.json, should return the same result than the releases page, maybe you can tell me if this is not the case.

## Current Behavior

So if yes, as you can see in the video above, the API's result is different than https://rubygems.org/news .
I think some results are here 3 or 4 times with differents 'platforms', this is not really disturbing. But some gems that are present in the releases page, are not present in the return of the API, and this can be disturbing.

## Possible Solution

Maybe this endpoint just not meant to show the same results ?

## Environment

Chrome 114.0.5735.248

**Comment by simi** [comment] 2023-07-25 23:24
Hello, I do agree this is confusing. Would you mind to explain, why do you think those 2 pages should share the content? Is it written anywhere (like in guides)?

Currently both are using different criteria to show the content. Maybe we can try to unify that. Which one do you think makes more sense?

- news https://github.com/rubygems/rubygems.org/blob/01debe5426642e17b3db89713bae0b1642cee348/app/controllers/news_controller.rb#L4-L10
https://github.com/rubygems/rubygems.org/blob/01debe5426642e17b3db89713bae0b1642cee348/app/models/rubygem.rb#L97-L102
- just updated https://github.com/rubygems/rubygems.org/blob/01debe5426642e17b3db89713bae0b1642cee348/app/controllers/api/v1/activities_controller.rb#L7-L10
https://github.com/rubygems/rubygems.org/blob/01debe5426642e17b3db89713bae0b1642cee348/app/models/version.rb#L145-L162

**Comment by Peuf54** [comment] 2023-07-26 09:08
Hi Simi,

Thanks for answering fast !

To be honest I don't see in what context the result of just_updated could be more relevant than /news.
My first intention would be to change the just_updated's method to get same results, but as you said, I don't have seen anywhere that both /news and just_updated should return the same results... 

Maybe the better choice is to create another endpoint /api/v1/activity/news.json ? I can try to do it if you think it's a good idea ? 

Kr,
Hugo

**Comment by simi** [comment] 2023-09-10 21:31
@Peuf54 if you're interested in this endpoint, feel free to open PR to enhance API. Meanwhile, since we have found out this is not actual bug, but it is expected behaviour, is it ok to close this issue?

**Closed** 2023-10-17 22:09 UTC
Labels: bug
