### ISSUE TITLE
OIDC: Create: Please consider explaining what this does.

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#4209] opened 2023-11-17 23:37 UTC
I just noticed a new link / entry, on the right side, called:

**OIDC: Create**

Right now I do not know what this is or does. The abbreviation does not tell me anything.

Clicking on it it asks me for my password (again?). I did not continue past this point
as I don't know what it does, so instead I came here and filed this issue request.

Would it be possible to provide an explanation what this does? Perhaps on a on-hover
action, show some modest pop-in or so, say after 3 or 4 seconds; and/or alternatively
a link towards the documentation explaining what this does.

Right now I think the situation is not ideal in that a developer may not know what this
(or another option) does.

Edit: First google result is https://docs.openathens.net/providers/ruby-openid-connect-example 
but I don't know if this is correct. I assume it has to do with open ID, but even then I am 
unsure what it does and why I need it.

**Comment by simi** [comment] 2023-11-18 00:30
dupe of https://github.com/rubygems/rubygems.org/issues/4127

**Closed by simi** 2023-11-18 00:30 UTC
Labels: feature
