### ISSUE TITLE
Certain admin panel actions do not work on packages with `.` in the name

### ISSUE THREAD

**Issue by mensfeld** [rubygems/rubygems.org#3984] opened 2023-08-11 07:49 UTC
## Steps to Reproduce

1. Go to admin panel
2. Try doing management work on `active_model_serializers_rails_2.3` or any other gem with version in name
3. 404

## Expected Behavior

I would expect to be able to do admin work and resources with dots should work.

## Current Behavior

404

## Possible Solution

Fix routing in Rails.

**Comment by simi** [comment] 2023-08-20 21:21
I did my best to investigate, but it seems we can't change Avo routing on our side (maybe @adrianthedev can confirm) to use different constraint (not classic `:id.:format`). And there is `to_param` implemented in `Rubygem` model not compatible with format, since it can contain `.`.

I was able to fix this using additional inherited Admin::Rubygem model and returning id as `to_param` again, but it broke other tests. Other idea is to rewrite routes to work without `to_param` implementation.

Any preferred suggestion how to fix this @segiddins?

**Comment by segiddins** [comment] 2023-08-20 21:48
Best way is to probably look into letting avo route mapper have different param formats per resource, same way we can do manually in our routes fileOn Aug 20, 2023, at 2:22 PM, Josef Šimánek ***@***.***> wrote:﻿
I did my best to investigate, but it seems we can't change Avo routing on our side (maybe @adrianthedev can confirm) to use different constraint (not classic :id.:format). And there is to_param implemented in Rubygem model not compatible with format, since it can contain ..
I was able to fix this using additional inherited Admin::Rubygem model and returning id as to_param again, but it broke other tests. Other idea is to rewrite routes to work without to_param implementation.
Any preferred suggestion how to fix this @segiddins?

**Comment by adrianthedev** [comment] 2023-08-21 12:14
Could you tweak the `find_record_method` to check the `format` params and recreate the `id`.

```ruby

  self.find_record_method = lambda { |model_class:, id:, params:| # rubocop:disable Lint/UnusedBlockArgument
    # Check if the format is a "version number" and recreate the id
    if params[:format].present?
      id = "#{params[:id]}.#{params[:format]}"
    end
    # This bit here 👆

    # In case of perfoming action `id` becomes an array of `ids`
    if id.is_a?(Array)
      model_class.where(id: id)
    else
      model_class.find_by!(name: id)
    end
  }
```

Of course, you should tweak the condition a bit to ensure it's a number and not an actual format.

**Comment by simi** [comment] 2023-08-21 12:18
> Could you tweak the `find_record_method` to check the `format` params and recreate the `id`.
> 
> ```ruby
>   self.find_record_method = lambda { |model_class:, id:, params:| # rubocop:disable Lint/UnusedBlockArgument
>     # Check if the format is a "version number" and recreate the id
>     if params[:format].present?
>       id = "#{params[:id]}.#{params[:format]}"
>     end
>     # This bit here 👆
> 
>     # In case of perfoming action `id` becomes an array of `ids`
>     if id.is_a?(Array)
>       model_class.where(id: id)
>     else
>       model_class.find_by!(name: id)
>     end
>   }
> ```
> 
> Of course, you should tweak the condition a bit to ensure it's a number and not an actual format.

I was thinking about merging back the format, but that's seems super hacky, since there can be real request for `json` format at some point for example. That's the reason we have custom constraint for this reason.

**Comment by adrianthedev** [comment] 2023-08-21 12:20
Would checking `params[:format].to_i` for being an integer sweeten the deal and make it less hacky?
So when you have `gem_1.5` that would merge the format in, and `gem1.json` would not.

**Comment by adrianthedev** [comment] 2023-08-21 12:22
Otherwise, I'm open to suggestions on how to accommodate this

**Comment by simi** [comment] 2023-08-21 12:26
Alternative idea would be to configure resource to use different identifier than `to_param` (since we can use IDs in admin instead).

**Comment by adrianthedev** [comment] 2023-08-21 13:09
You are correct, we don't have that mechanism to pass options to the routes.

The custom `to_param` method would be a bit too much for us to add. We sometimes just generate the routes using the helpers, which in term use `to_param`.
Same for future releases. Every time someone (us or a contributor) writes a route using a route helper, they will forget to use the custom `to_param` method, and that will lead to messy and un-maintainable releases.

I would give the `find_record_method` another chance. That should yield the best results.

The route options way on the `resources` route will not yield the best results. 
I have a PoC PR where we'll have multiple `resources` statements to cover all the associations and attachments to support the namespaced resources use-case `Super::Dooper::Trooper::UserResource`. Not sure what results we'll have adding the same options to all nested routes.

**Comment by simi** [comment] 2023-08-22 19:26
If this should be fixed and there is no plan to make this configurable on Avo side, I suggest to remove `to_param` method and do the same manually in codebase. I'll open draft PR to explain code-wise.

**Comment by adrianthedev** [comment] 2023-08-24 19:04
Hmm. I don't understand why we would remove `to_param`. Isn't that what's being used to generate routes using the route helpers?
But some context would help. Looking forward to the PR.

**Comment by simi** [comment] 2023-08-24 19:06
> Hmm. I don't understand why we would remove `to_param`. Isn't that what's being used to generate routes using the route helpers? But some context would help. Looking forward to the PR.

I mean to remove to_param from RubyGems.org codebase, that way it will rely back on ID and everything will work as intended. For places we would like to use custom identifier, we can pass it explicitly (we do already for `Version` model).

**Comment by adrianthedev** [comment] 2023-08-24 19:07
Oh. Ok. Got it!
I misunderstood. Thanks!

**Closed** 2023-08-31 21:35 UTC
Labels: bug
