### ISSUE TITLE
[Feature request] Add the ability to show statistics per gem release, ideally via a graph, but at base minimum on a per-day download

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#3003] opened 2022-04-02 23:21 UTC
Hey there rubygems.org maintainers,

This idea has been partially inspired by bestgems.org, such as:

https://bestgems.org/gems/bundler

I am **not** suggesting to clone/copy-paste the code as-is, although that may be an option
I think (the code is available as far as I know). But, instead, I want to only point out at the
**graph example** there that shows how things change over days and weeks. I'd like to
have something like this on rubygems.org for my gems.

I am **not** suggesting that this functionality should be the same, mind you. I think a simplified
version would be just fine, say, every 3 days or just weekly download stats. If making a graph
is too much work for now, then perhaps just the numbers, to show daily downloads. Then once
that data is available, it may be easy to just load this into some javascript graph library or 
something.

Where would I propose that graph or statistic dataset as API?

Well; if we pick the example of bundler, at rubygems.org, say the following URL:

https://rubygems.org/gems/bundler

Then I believe a new sub-URL can be added called:

https://rubygems.org/gems/bundler/statistics

That is "statistics" as verb should tell us some statistics. This could be more generic,
so not just daily downloads or weekly downloads but it may contain more information.
That is, it could be extended at a later time. But, for the time being, I propose it to
refer to the weekly downloads, of some sorts.

I am not sure how useful that suggestion here may be, so if anyone else thinks that
this could be interesting, please comment or upvote (however you prefer). I assume
this may only have a chance to be implemented if several ruby devs/users may feel
this is useful. And again: I am not proposing it to be the same as the one on 
bestgems.org. Just anything that is simple and tells a gem author when a gem is
downloaded more often than others. This may also help gauge how many active
users there are, as in my experience most early downloads come from bots and
scripts syncing some mirror or something.

**Comment by sonalkr132** [comment] 2022-04-06 03:40
Duplicate of https://github.com/rubygems/rubygems.org/issues/1483.
If you would like us to read your report in more detail, please follow the feature request template.

**Closed by sonalkr132** 2022-04-06 03:40 UTC
Labels: feature
