### ISSUE TITLE
Update blog with the new design from rubygems.org

### ISSUE THREAD

**Issue by chasecoolman** [rubygems/rubygems.org#1213] opened 2016-03-04 17:58 UTC
Originally mentioned here https://trello.com/c/qI86IUdL/53-update-blog-rubygems-org-with-the-new-design-from-rubygems-org by @arthurnn @anatolinicolae

blog.rubygems.com is outdated and no longer matches the rest of the site.

**Comment by dwradcliffe** [comment] 2016-03-04 18:04
Duplicate of #863

**Closed by dwradcliffe** 2016-03-04 18:04 UTC
