### ISSUE TITLE
Remain signed in to rubygems.org for a longer while?

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1674] opened 2017-09-14 16:42 UTC
Hello folks,

Not sure if it is set by a cookie, or my old browser - but for whatever reason, after signing in,
I seem to be signed in only for some somewhat short amount of time, perhaps 30 minutes or so.

I often have several tabs open in my browser, so I usually have to re-sign in again after that
time period.

I'd like to be signed in for longer, hence my suggestion.

- Could the default be extended? I'd like to be signed in for several hours :D like in the morning, to login and remain signed in. Reason being largely out of convenience; when signed in, I can get to see when I made updates to any of my gems, which helps a bit in making sure that these gems also work (and that I did not forget to update any of my gems for that day).

It's nothing very important, just something for convenience.

**Comment by colby-swandale** [comment] 2017-10-18 12:05
This seems like a bug as we set the auth cookie to expire 2 weeks after the login

**Comment by manuelmeurer** [comment] 2017-10-22 21:42
I experience this as well. I have to sign in every time I go to rubygems.org, even if it's multiple times on the same day... using latest Chrome on macOS.

**Comment by dwradcliffe** [comment] 2017-10-22 21:49
Seems like mine lasts for several months. It would be great if someone could look into this and see what it’s supposeed to be doing.

**Comment by colby-swandale** [comment] 2017-10-22 23:04
I think i have a fix for this. PR incoming

**Comment by colby-swandale** [comment] 2017-10-25 13:15
@shevegen @manuelmeurer are you by any chance logging into rubygems using different browsers/machines?

The issue i think is that only a single auth token can be used for any one account, so when you login on a different browser/machine any existing login session is immediately overwritten.

**Comment by manuelmeurer** [comment] 2017-10-25 13:21
Hmm no, I always use the same machine and browser.

**Comment by colby-swandale** [comment] 2017-10-29 12:43
I've been trying to reproduce this but i've had no luck in doing so. Any more information about this would be appreciated

**Comment by manuelmeurer** [comment] 2017-10-29 13:32
Here's a screenshot of my cookies: 
![image](https://user-images.githubusercontent.com/16672/32144228-ffe034ee-bcb5-11e7-90d8-23d66749b6b1.png)
Does that help?

**Comment by manuelmeurer** [comment] 2018-04-11 10:40
Ok, I checked it with Firefox for a few days now (normally I use Chrome), even there I'm logged out every day... so the browser is probably not the problem.

@colby-swandale You mentioned when I log in with another browser/machine, a new auth token is created and I'm logged out on all other machines.
Is it possible to see in the logs, when (and from which browser/machine) logins for my account are done? If yes, could you share them with me? (manuel@krautcomputing.com)

**Comment by sonalkr132** [comment] 2018-06-29 04:53
We recently fixed session being destroyed when an api request it made (#1739). Seemingly Random log out should be fixed when my PR is deployed to prod.
> when you login on a different browser/machine any existing login session is immediately overwritten.

This is intended behaviour. We don't support multiple login sessions. If you feel like this is something we need, please open a new issue or even better a PR.

**Closed by sonalkr132** 2018-06-29 04:53 UTC
Labels: bug
