### ISSUE TITLE
SSL-Certificate-Update process fails to update gem to 2.6.7

### ISSUE THREAD

**Issue by baob** [rubygems/rubygems.org#1460] opened 2016-10-12 16:40 UTC
I'm following [this process](http://guides.rubygems.org/ssl-certificate-update/)

In my case, the gem does not update to 2.6.7. I've looked up advice on the only error message, the only advice suggests I might be erroneously referencing rubyforge , not true in my case.

```
$ rvm --version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ gem --version
2.6.1

$ gem install --local ~/Downloads/rubygems-update-2.6.7.gem
Successfully installed rubygems-update-2.6.7
1 gem installed

$ gem --version
2.6.1

$ update_rubygems --no-ri --no-rdoc
Error: Cannot find RubyGems Update Path!

RubyGems has already been updated.
The rubygems-update gem may now be uninstalled.
E.g.    gem uninstall rubygems-update

$ gem --version
2.6.1
```
Related to the error message 
```
$ gem sources
*** CURRENT SOURCES ***

https://rubygems.org/

$ cat ~/.gemrc
gem: --no-document
```

**Comment by sonalkr132** [comment] 2016-10-12 17:05
For what its worth, I could not reproduce this.
Try `gem uninstall rubygems-update`. if multiple versions are installed choose:
> 3 . All versions

Install rubygem-update-2.6.7 again and `update_rubygems`.

**Comment by baob** [comment] 2016-10-12 17:30
Unfortunately `gem uninstall rubygems-update`  made no difference

**Comment by sonalkr132** [comment] 2016-10-12 17:51
>  I could not reproduce this.

:scream: I had rubygem 2.6.6. Updating of 2.6.1 doesn't work for any of versions from 2.6.2 to 2.6.7.
> Error: Cannot find RubyGems Update Path!
RubyGems has already been updated.
The rubygems-update gem may now be uninstalled.
E.g.    gem uninstall rubygems-update

Will update when I have more info :+1:

**Comment by dwradcliffe** [comment] 2016-10-12 17:52
This probably needs to move to the other repo. (rubygems/rubygems)
cc: @segiddins @drbrain

**Comment by sonalkr132** [comment] 2016-10-12 18:02
@baob Found this https://github.com/rubygems/rubygems/issues/1533

```
$ which update_rubygems
~/.rvm/gems/ruby-2.3.1/bin/update_rubygems
```

Replace line 11 ( `version = ">= 0.a"`) of `update_rubygems` script with:
```Ruby
gem 'rubygems-update', version = ">= 0.a"
```
```diff
Run `update_rubygems`.

**Comment by dwradcliffe** [comment] 2016-10-12 18:03
Good find! I'm going to close this, any further discussion can happen on that issue.

**Closed by dwradcliffe** 2016-10-12 18:03 UTC

**Comment by baob** [comment] 2016-10-12 18:26
@sonalkr132 That solves it for me, thanks. Will check the other issue as needed.
