### ISSUE TITLE
Installing gem does not install all gem dependencies

### ISSUE THREAD

**Issue by blowmage** [rubygems/rubygems.org#1489] opened 2016-11-09 16:44 UTC
Hey all, we are having a problem with a dependency not being listed in the `dependencies` API call. This is causing an error when installing the `google-cloud` gem because not all the gem's declared dependencies are installed. Even though the dependency is properly listed in the gemspec and on the rubygems site. Moar details below.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### Moar details

The gem that is not being installed is `google-cloud-error_reporting`. The dependency is listed on the rubygems site, and on the gem API.

https://rubygems.org/gems/google-cloud
https://rubygems.org/api/v1/gems/google-cloud.json

However, when installing the gem the rubygems CLI makes a call to retrieve all the dependencies, and the `google-cloud-error_reporting` dependency is *NOT* listed in that API call.

https://api.rubygems.org/api/v1/dependencies.json?gems=google-cloud

Once all the dependencies are installed, the CLI tries to install the `google-cloud` gem but errors due to the missing dependency.

```
$ gem install google-cloud
Fetching: google-cloud-core-0.21.0.gem (100%)
Successfully installed google-cloud-core-0.21.0
Fetching: uber-0.0.15.gem (100%)
Successfully installed uber-0.0.15
Fetching: representable-2.3.0.gem (100%)
Successfully installed representable-2.3.0
Fetching: retriable-2.1.0.gem (100%)
Successfully installed retriable-2.1.0
Fetching: mime-types-data-3.2016.0521.gem (100%)
Successfully installed mime-types-data-3.2016.0521
Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Fetching: hurley-0.2.gem (100%)
Successfully installed hurley-0.2
Fetching: little-plugger-1.1.4.gem (100%)
Successfully installed little-plugger-1.1.4
Fetching: logging-2.1.0.gem (100%)
Successfully installed logging-2.1.0
Fetching: memoist-0.15.0.gem (100%)
Successfully installed memoist-0.15.0
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: signet-0.7.3.gem (100%)
Successfully installed signet-0.7.3
Fetching: googleauth-0.5.1.gem (100%)
Successfully installed googleauth-0.5.1
Fetching: httpclient-2.8.2.4.gem (100%)
Successfully installed httpclient-2.8.2.4
Fetching: google-api-client-0.9.20.gem (100%)
Successfully installed google-api-client-0.9.20
Fetching: google-cloud-bigquery-0.21.0.gem (100%)
Successfully installed google-cloud-bigquery-0.21.0
Fetching: google-protobuf-3.0.2-universal-darwin.gem (100%)
Successfully installed google-protobuf-3.0.2-universal-darwin
Fetching: grpc-1.0.1-universal-darwin.gem (100%)
Successfully installed grpc-1.0.1-universal-darwin
Fetching: googleapis-common-protos-1.3.4.gem (100%)
Successfully installed googleapis-common-protos-1.3.4
Fetching: rly-0.2.3.gem (100%)
Successfully installed rly-0.2.3
Fetching: google-gax-0.6.0.gem (100%)
Successfully installed google-gax-0.6.0
Fetching: google-cloud-datastore-0.21.0.gem (100%)
Successfully installed google-cloud-datastore-0.21.0
Fetching: zonefile-1.04.gem (100%)
Successfully installed zonefile-1.04
Fetching: google-cloud-dns-0.21.0.gem (100%)
Successfully installed google-cloud-dns-0.21.0
Fetching: google-cloud-language-0.21.0.gem (100%)
Successfully installed google-cloud-language-0.21.0
Fetching: orderedhash-0.0.6.gem (100%)
Successfully installed orderedhash-0.0.6
Fetching: google-cloud-logging-0.21.1.gem (100%)
Successfully installed google-cloud-logging-0.21.1
Fetching: google-cloud-monitoring-0.21.0.gem (100%)
Successfully installed google-cloud-monitoring-0.21.0
Fetching: grpc-google-iam-v1-0.6.8.gem (100%)
Successfully installed grpc-google-iam-v1-0.6.8
Fetching: google-cloud-pubsub-0.21.0.gem (100%)
Successfully installed google-cloud-pubsub-0.21.0
Fetching: google-cloud-resource_manager-0.21.0.gem (100%)
Successfully installed google-cloud-resource_manager-0.21.0
Fetching: google-cloud-speech-0.21.0.gem (100%)
Successfully installed google-cloud-speech-0.21.0
Fetching: google-cloud-storage-0.21.0.gem (100%)
Successfully installed google-cloud-storage-0.21.0
Fetching: google-cloud-translate-0.21.0.gem (100%)
Successfully installed google-cloud-translate-0.21.0
Fetching: google-cloud-vision-0.21.1.gem (100%)
Successfully installed google-cloud-vision-0.21.1
Fetching: google-cloud-0.21.0.gem (100%)
ERROR:  Error installing google-cloud:
	google-cloud requires google-cloud-error_reporting (~> 0.21.0)
```

**Comment by blowmage** [comment] 2016-11-09 19:23
So I just realized that https://rubygems.org/api/v1/gems/google-cloud.json is showing version 0.21.0, which added the dependency on `google-cloud-error_reporting`, but https://api.rubygems.org/api/v1/dependencies.json?gems=google-cloud is showing an older version, 0.20.1, which does not have the dependency. So the problem is not that the `dependency` API is showing the wrong dependencies, but that it is showing the dependencies for the wrong version.

**Comment by blowmage** [comment] 2016-11-09 19:30
Ugh, I was wrong. https://api.rubygems.org/api/v1/dependencies.json?gems=google-cloud is showing versions 0.20.1, then 0.21.0, then 0.20.0. The versions are just listed out of order. Are they supposed to be in order?

Either way, the 0.21.0 gem doesn't list the `google-cloud-error_reporting` dependency like it should.

**Comment by blowmage** [comment] 2016-11-09 20:48
I looked into the API rails app, but in the end we couldn't wait to figure out how to flush the cached dependencies payload, so we pushed out a new released for `google-cloud`, and that looks to have updated the cache. Both the existing 0.21.0 and the new 0.21.1 release now show the `google-cloud-error_reporting` dependency.

It would be very useful to be able to clear the dependency cache for a gem outside of pushing a new version.

**Comment by sonalkr132** [comment] 2016-11-10 08:59
> when installing the gem the rubygems CLI makes a call to retrieve all the dependencies, and the google-cloud-error_reporting dependency is NOT listed in that API call.

It seems unlikely that it was because we couldn't clear rails cache.
Had our dependency cache not expired [after you pushed `0.21.0`](https://github.com/rubygems/rubygems.org/blob/master/app/models/pusher.rb#L135), you would not have seen google-cloud `0.21.0` version in our dependency response
```json
 {
  "name": "google-cloud",
  "number": "0.21.0",
  "platform": "ruby",
  "dependencies": [
    ...
  ]
}
```
All of this :arrow_up: would not be there, not just one requirement.

I think for some reason `row['dep_name']` in [following line](https://github.com/rubygems/rubygems.org/blob/master/app/models/gem_dependent.rb#L46) was `nil` when `google-cloud-error_reporting` requirement was to be added.
```Ruby
deps[key] << [row['dep_name'], row['requirements']] if row['dep_name']
```

It would be very difficult to fix unless we get more similar reports. Sorry.

**Comment by sonalkr132** [comment] 2020-04-06 22:10
Closing for lack of reproducible steps. Please update with steps to reproduce this and we can take another look.

**Closed by sonalkr132** 2020-04-06 22:10 UTC
Labels: api

**Comment by blowmage** [comment] 2020-04-07 01:02
This was a cache issue. If we pushed gem A with a dependency on gem B, with version C _before_ gem B version C was pushed, the API would consider that dependency invalid. Even when gem B version C was pushed the dependency on it in gem A was never handled properly by the API. It wasn't until a new version of gem A was pushed that the API updated the dependencies.

**Comment by sonalkr132** [comment] 2020-04-07 14:03
Thank you for update @blowmage I could not reproduce it with steps you provided, A = hola, B = holaa and C = 0.0.2
```
$ RUBYGEMS_HOST=http://localhost:3000 gem push hola-3.10.66.gem
Pushing gem to http://localhost:3000...
Successfully registered gem: hola (3.10.66)
$ RUBYGEMS_HOST=http://localhost:3000 gem install hola -v 3.10.66
ERROR:  Could not find a valid gem 'holaa' (= 0.0.2) (required by 'hola' (= 3.10.66)) in any repository
ERROR:  Possible alternatives: holaa
$ gem build holaa.gemspec 
  Successfully built RubyGem
  Name: holaa
  Version: 0.0.2
  File: holaa-0.0.2.gem
$ RUBYGEMS_HOST=http://localhost:3000 gem push holaa-0.0.2.gem 
Pushing gem to http://localhost:3000...
Successfully registered gem: holaa (0.0.2)
$ RUBYGEMS_HOST=http://localhost:3000 gem install hola -v 3.10.66
Successfully installed holaa-0.0.2
Successfully installed hola-3.10.66
Parsing documentation for holaa-0.0.2
Installing ri documentation for holaa-0.0.2
Parsing documentation for hola-3.10.66
Installing ri documentation for hola-3.10.66
Done installing documentation for holaa, hola after 7 seconds
2 gems installed
```
