### ISSUE TITLE
Can't install gems from https://rubygems.org/ source

### ISSUE THREAD

**Issue by rezam90** [rubygems/rubygems.org#1112] opened 2015-11-18 04:57 UTC
I can't install gems from rubygems, but other sources works well with low speed.
it gives me this error:

`gem install grape -V`
```
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=grape
200 OK
GET https://api.rubygems.org/quick/Marshal.4.8/grape-0.13.0.gemspec.rz
302 Moved Temporarily
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/grape-0.13.0.gemspec.rz)
```
but when I connect through VPN or proxy, installation works correctly.
I'm from Iran, have you guys blocked connections from Iran?

**Comment by dwradcliffe** [comment] 2015-11-18 11:56
We are not blocking Iran. Can you view the website ok?

**Comment by rezam90** [comment] 2015-11-18 14:30
@dwradcliffe, the website is ok.
I had no problems since about 5-6 weeks ago.

**Comment by nateberkopec** [comment] 2015-11-18 16:43
Diagnosing possible governmental firewalling is way out of my comfort zone, but FWIW, I can make requests successfully to rubygems.org and the production S3 bucket when using an Iranian proxy IP:

```
$ http_proxy=91.98.143.85:8080 curl -I https://s3.amazonaws.com/production.s3.rubygems.org
HTTP/1.1 200 OK
```

It's interesting that this appears to be failing at the fastly layer for you, @rezam90. The failed request in your shared output above would have been to `https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/grape-0.13.0.gemspec.rz`. Again, I can't repro this with an Iranian proxy.

**Comment by nateberkopec** [comment] 2015-11-18 16:45
Also, I am not a lawyer, but might this have something to do with [Fastly's TOS](https://www.fastly.com/terms)?

> 12. Export Compliance. The Services and Documentation may be subject to export laws and regulations of the United States and other jurisdictions. Each party represents that it is not named on any U.S. government denied-party list. Subscriber shall not enable use of the Services in a U.S.-embargoed country (currently Cuba, Iran, North Korea, Sudan, or Syria) or in violation of any U.S. export law or regulation.

**Comment by dwradcliffe** [comment] 2015-11-18 16:52
A good test might be http://www.fastly-debug.com/

**Comment by drbrain** [comment] 2015-11-18 18:14
It's more likely that Iran blocks access to Fastly.  I believe the Fastly TOS prevents Fastly from selling service to customers in these countries and prevents a customer of Fastly from using Fastly to serve content originating in these countries.

**Comment by rezam90** [comment] 2015-11-18 19:57
@drbrain, Iran does not block Fastly, blocked websites shows or redirects to a forbidden page. I think it's Fastly that blocked Iran as @nateberkopec said. but
@dwradcliffe, the test stucks in "Collecting data please wait..." with a few details:
```
IP:	151.244.163.102
AS Name	:
AS Number:	
BGP Prefix:	
City:	
Continent:
Country:	
State :	
Resolver IP Info:
IP:	
AS Name:	
AS Number:	
BGP Prefix:	
Country Code:	
Server IP Info:
IP:	185.31.17.64
Datacenter:	FRA
BW to server:	
Request Info:
Time:	Wed Nov 18 2015 23:05:36 GMT+0330 (Iran Standard Time)
Host:	www.fastly-debug.com
Accept:	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Accept-Language:	en-US,en;q=0.8,fa;q=0.6
Accept-Encoding:	gzip
X-Forwarded-For:
```
Thank you guys, but any solution for this?

**Comment by drbrain** [comment] 2015-11-18 20:38
None of the Iranian RIPE Atlas probes can connect to Fastly over SSL: https://atlas.ripe.net/measurements/2976639/#!probes

Talking to my coworkers, we don't block inbound requests.  We think Iran's border routers are black-holing SSL traffic to Fastly, but have not investigated further.

You can contact [Fastly support](https://www.fastly.com/support) for help diagnosing this issue.

**Comment by nateberkopec** [comment] 2015-11-19 01:28
(Should one of us be talking to Fastly? @dwradcliffe?)

@rezam90 As a workaround, since the issue is with Fastly over SSL, you can try using a non-secured connection:

```
source "http://rubygems.org"
```

...with all the caveats that entails.

You may also try an SSL connection straight to the Amazon S3 bucket. This will be considerably slower, I think, but at least you'll have a secure connection.

```
source 'https://s3.amazonaws.com/production.s3.rubygems.org'
```

**Comment by rezam90** [comment] 2015-11-19 05:48
@nateberkopec, thank you. the non-secured connection using `http://rubygems.org` works great, and I think I'm OK with that. I didn't know I could use the `http` one.

I tried the `https://s3.amazonaws.com/production.s3.rubygems.org` source which caused this error:
```
gem sources -a 'https://s3.amazonaws.com/production.s3.rubygems.org'
Error fetching https://s3.amazonaws.com/production.s3.rubygems.org:
        SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (https://s3.amazonaws.com/specs.4.8.gz)
```
Thanks BTW.

**Comment by drbrain** [comment] 2015-11-19 16:38
I think @rezam90 is the best person to contact support because they can answer the questions Fastly might have.

**Comment by dwradcliffe** [comment] 2015-11-19 16:40
Yep. I'm going to close this issue. Please follow up with Fastly. If you need additional help, please open a help ticket at http://help.rubygems.org/

**Closed by dwradcliffe** 2015-11-19 16:40 UTC

**Comment by WimTenBrink** [comment] 2016-01-29 13:49
Guys, read http://knowledgelayer.softlayer.com/faq/softlayer-network-wide-ip-blocking
IBM Softlayer recently started blocking several states including Iran. It could be that several sites are within the Softlayer IP range and are thus using Softlayer as ISP.

**Comment by dwradcliffe** [comment] 2016-01-29 13:51
I'm not sure what Softlayer has to do with this. We don't use Softlayer or Softlayer IPs.

**Comment by WimTenBrink** [comment] 2016-01-29 14:01
It could be that Amazon is doing the same. As a result, several foreign states would be blocked by the ISP.
